spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sigobius  # URL de conexión MySQL/MariaDB
    username: root  # Usuario de la base de datos
    password: 1234  # Contraseña de la base de datos
    driver-class-name: com.mysql.cj.jdbc.Driver  # Driver JDBC para MySQL/MariaDB
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update  # Puedes usar 'validate', 'create', 'update', etc.
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect  # Dialecto adecuado para MySQL
